[default]
README_VERSION = '0.0.1'
USER = 'alves-dev'
API_BASE_URL = 'https://api.github.com'


[development]
USER = 'alves-dev'
API_BASE_URL = 'https://api.github.com'

[production]
USER = 'alves-dev'
API_BASE_URL = 'https://api.github.com'